// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxmrhblreudhbsakpdkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bXJoYmxyZXVkaGJzYWtwZGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTI3NTAsImV4cCI6MjA2MTQ4ODc1MH0.ea2ZVPF-l79RgCLr-OcZgXvR2C1KHvDrDAH3mEAzEGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);